name: buildx

on:
  push:
    branches:
    - test-gha # to be deleted after test
    tags:
    - "*"
  schedule:
    - cron: "0 0 * * *"

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Checkout shasta source code
        uses: actions/checkout@v2
        with:
          ref: ${{ env.GITHUB_REF_NAME }}
          repository: chanzuckerberg/shasta
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up version for releases
        if: ${{ github.ref_name != 'main' }}
        run: echo SHASTA_VERSION=${GITHUB_REF_NAME} >> $GITHUB_ENV
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build and push image
        run: >
          docker buildx build
          --push
          --tag ghcr.io/chanzuckerberg/shasta:{SHASTA_VERSION:-latest}
          --platform linux/amd64,linux/arm64
          .